name: Stack Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ghc: ['9.8.4'] # ['9.6.4', '9.8.4', '9.12.2'] # '9.2.7', '9.4.8', 
        cabal: ['3.10.2.1'] # ['3.6.2.0', '3.10.2.1']
        stack: ['latest']  # ['2.9.3', 'latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        deps: ['stack-fp-141-os-202.yaml','stack-fp-141-os-207.yaml','stack-fp-143-os-201.yaml','stack-fp-154-os-204.yaml','stack-fp-154-os-208.yaml']
        include:
          - deps: 'stack-fp-141-os-202.yaml'
            vern: 'fp-141 os-202'
          - deps: 'stack-fp-141-os-207.yaml'
            vern: 'fp-141 os-207'
          - deps: 'stack-fp-143-os-201.yaml'
            vern: 'fp-143 os-201'
          - deps: 'stack-fp-154-os-204.yaml'
            vern: 'fp-154 os-204'
          - deps: 'stack-fp-154-os-204.yaml'
            vern: 'fp-154 os-208'
          - os: 'ubuntu-latest'
            plat: 'linux'
          - os: 'windows-latest'
            plat: 'windows'
          - os: 'macOS-latest'
            plat: macOS
          # Manual additions (9.10.3)
          - ghc: '9.10.3'
            deps: 'alt-ghc/stack-ghc-9-10-a.yaml'
            vern: 'fp-154 os-208'
            os: ubuntu-latest
            plat: linux
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.10.3'
            deps: 'alt-ghc/stack-ghc-9-10-a.yaml'
            vern: 'fp-154 os-208'
            os: windows-latest
            plat: windows
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.10.3'
            deps: 'alt-ghc/stack-ghc-9-10-a.yaml'
            vern: 'fp-154 os-208'
            os: macOS-latest
            plat: macOS
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.10.3'
            deps: 'alt-ghc/stack-ghc-9-10-b.yaml'
            vern: 'fp-143 os-208'
            os: ubuntu-latest
            plat: linux
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.10.3'
            deps: 'alt-ghc/stack-ghc-9-10-b.yaml'
            vern: 'fp-143 os-208'
            os: windows-latest
            plat: windows
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.10.3'
            deps: 'alt-ghc/stack-ghc-9-10-b.yaml'
            vern: 'fp-143 os-208'
            os: macOS-latest
            plat: macOS
            cabal: '3.10.2.1'
            stack: 'latest'
          # Manual additions (9.12.2)
          - ghc: '9.12.2'
            deps: 'alt-ghc/stack-ghc-9-12-a.yaml'
            vern: 'fp-154 os-208'
            os: ubuntu-latest
            plat: linux
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.12.2'
            deps: 'alt-ghc/stack-ghc-9-12-a.yaml'
            vern: 'fp-154 os-208'
            os: windows-latest
            plat: windows
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.12.2'
            deps: 'alt-ghc/stack-ghc-9-12-a.yaml'
            vern: 'fp-154 os-208'
            os: macOS-latest
            plat: macOS
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.12.2'
            deps: 'alt-ghc/stack-ghc-9-12-b.yaml'
            vern: 'fp-143 os-208'
            os: ubuntu-latest
            plat: linux
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.12.2'
            deps: 'alt-ghc/stack-ghc-9-12-b.yaml'
            vern: 'fp-143 os-208'
            os: windows-latest
            plat: windows
            cabal: '3.10.2.1'
            stack: 'latest'
          - ghc: '9.12.2'
            deps: 'alt-ghc/stack-ghc-9-12-b.yaml'
            vern: 'fp-143 os-208'
            os: macOS-latest
            plat: macOS
            cabal: '3.10.2.1'
            stack: 'latest'

      #deps:
      #  filepath: ["filepath-1.5.4.0", "filepath-1.4.101.0", "filepath-1.4.301.0"]
      #  osstring: ["os-string-2.0.1", "os-string-2.0.4", "os-string-2.0.6", "os-string-2.0.8"]

    name: GHC ${{ matrix.ghc }} ${{ matrix.plat }} ${{ matrix.vern }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          stack-version: ${{ matrix.stack }}
          enable-stack: true
      - name: Get stack.yaml version
        run: |
          mv stack.yaml stack-bkup.yaml
          cp alt-setup/${{ matrix.deps }} stack.yaml
      - name: Build dependencies
        run: stack test --only-dependencies
      - name: Build code
        run: stack build --ghc-options "-Wno-unused-imports -Wno-identities -Wno-deprecations"
      - name: Run Tests
        run: stack test --ghc-options "-Wno-unused-imports -Wno-identities -Wno-deprecations"
      # Maybe find a way to only benchmark a couple runs.
      # - name: Run benchmarks
      #   run: stack build --bench
      - name: Revert stack.yaml
        run: |
          rm stack.yaml
          mv stack-bkup.yaml stack.yaml

#    steps:
#    - uses: actions/checkout@v4
#    - uses: actions/setup-haskell@v1
#      with:
#        ghc-version: ${{ matrix.ghc }}
#        cabal-version: ${{ matrix.cabal }}
#        enable-stack: true

#    - name: Haskell GHC ${{ matrix.ghc }} on ${{ matrix.os }}
#      uses: actions/cache@v3
#      env:
#        cache-name: cache-cabal
#      with:
#        path: ~/.cabal
#        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
#        restore-keys: |
#          ${{ runner.os }}-build-${{ env.cache-name }}-
#          ${{ runner.os }}-build-
#          ${{ runner.os }}-

#    - name: Install dependencies
#      run: |
#        stack test --only-dependencies # --enable-tests --enable-benchmarks
#    - name: Build
#      run: stack build # --enable-tests --enable-benchmarks all
#    - name: Run tests
#      run: stack test # all
